// Frameworks/vue/casa-rural/app/components/header.vue
<script type="ts" setup>
import Container from './layout/container.vue';
import Logo from './logo.vue'
</script>

<template>
    <header class="bg-bg-white border-b-2 border-b-border">
        <Container>
            <NuxtLink to="/">
                <div class="flex justify-between flex items-center h-16">
                    <Logo />
                </div>
            </NuxtLink>
        </Container>
    </header>
</template>

// Frameworks/react/casa-rural/src/components/header.tsx
import { Link } from 'next-view-transitions'
import { Container } from '@/components/container'
import { Logo } from '@/components/logo'

export function Header() {
  return (
    <header className="bg-surface border-b-2 border-b-border">
      <Container>
        <Link href="/">
          <div className="flex justify-between items-center h-16">
            <Logo />
          </div>
        </Link>
      </Container>
    </header>
  )
}
