// Frameworks/react/casa-rural/src/components/house-detail/house-detail-item.tsx
interface HouseDetailItemProps {
  title: string
  isInline?: boolean
  content?: string | number
}

export function HouseDetailItem({ title, isInline = false, content }: HouseDetailItemProps) {
  if (content === undefined || content === null || content === '') return null

  return (
    <div
      className={`flex flex-col mb-4 pb-5 ${isInline ? 'flex-row items-center' : ''}`}
    >
      <h2 className={`text-lg font-bold ${isInline ? 'mr-2 mb-0' : 'mb-2'}`}>
        {title}
        {isInline && ':'}
      </h2>
      <p>{content}</p>
    </div>
  )
}

// Frameworks/vue/casa-rural/app/components/house-detail-item.vue
<script lang="ts" setup>

const { title, isInline = false, content } = defineProps<{
    title: string
    isInline?: boolean
    content?: string | number
}>()

const wrapperClasses = computed(() => {
    return {
        'flex-row items-center': isInline
    }
})

const titleClasses = computed(() => {
    return {
        'mb-2': !isInline,
        'mr-2 mb-0': isInline
    }
})
</script>

<template>
    <div v-if="content" class="flex flex-col mb-4 pb-5" :class="wrapperClasses">
        <h2 class="text-lg font-bold" :class="titleClasses">{{ title }}<span v-if="isInline">:</span></h2>
        <p>{{ content }}</p>
    </div>
</template>
